[package]
name = "qubic-tcp-types"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getrandom = { version = "*", features = ["js"] }
serde = { version = "*", features = ["derive"] }
rand = { version = "*" }
qubic-types = { path= "../qubic-types" }
kangarootwelve = "0.1.2"

[features]
serde = ["qubic-types/serde"]
wasm = []